apiVersion: "authentication.istio.io/v1alpha1"
kind: MeshPolicy
metadata:
  name: default
spec:
  peers:
  - mtls: {}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "default"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
 name: prom-disable-auth
spec:
 host: prometheus.istio-system.svc.cluster.local
 trafficPolicy:
   tls:
     mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
 name: grafana-disable-auth
spec:
 host: grafana.istio-system.svc.cluster.local
 trafficPolicy:
   tls:
     mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
 name: api-server
spec:
 host: kubernetes.default.svc.cluster.local
 trafficPolicy:
   tls:
     mode: DISABLE