kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: edges.config.istio.io
  labels:
    package: edge
    istio: mixer-instance
spec:
  group: config.istio.io
  names:
    kind: edge
    plural: edges
    singular: edge
  scope: Namespaced
  version: v1alpha2
---
# Configuration for default graph edge
apiVersion: "config.istio.io/v1alpha2"
kind: edge
metadata:
  name: default
  namespace: istio-system
spec:
  timestamp: request.time
  sourceUid: source.uid | "Unknown"
  sourceOwner: source.owner | "Unknown"
  sourceWorkloadName: source.workload.name | "Unknown"
  sourceWorkloadNamespace: source.workload.namespace | "Unknown"
  destinationUid: destination.uid | "Unknown"
  destinationOwner: destination.owner | "Unknown"
  destinationWorkloadName: destination.workload.name | "Unknown"
  destinationWorkloadNamespace: destination.workload.namespace | "Unknown"
  contextProtocol: context.protocol | "Unknown"
  apiProtocol: api.protocol | "Unknown"
---
apiVersion: "config.istio.io/v1alpha2"
kind: stackdriver
metadata:
  name: context-handler
  namespace: istio-system
spec:
  project_id: csm-metrics-test
  service_account_path: /sd-account/sa.json
---
# Rule to send edge instances to the stackdriver handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: edgetosd
  namespace: istio-system
spec:
  match: (context.protocol | "unknown") != "unknown" # match for all requests
  actions:
   - handler: context-handler.stackdriver
     instances:
     - default.edge
