apiVersion: "config.istio.io/v1alpha2"
kind: stackdriver
metadata:
  name: context-handler
  namespace: istio-system
spec:
  project_id: csm-metrics-test
  service_account_path: /sd-account/sa.json
---
apiVersion: "config.istio.io/v1alpha2"
kind: stackdriver
metadata:
  name: context-handler-stage
  namespace: istio-system
spec:
  endpoint: staging-contextgraph.sandbox.googleapis.com:443
  project_id: csm-metrics-test
  service_account_path: /sd-account/sa.json
---
apiVersion: "config.istio.io/v1alpha2"
kind: edge
metadata:
  name: default
  namespace: istio-system
spec:
  timestamp: request.time | context.time
  sourceUid: source.uid | "Unknown"
  sourceOwner: source.owner | "Unknown"
  sourceWorkloadName: source.workload.name | "Unknown"
  sourceWorkloadNamespace: source.workload.namespace | "Unknown"
  destinationUid: destination.uid | "Unknown"
  destinationOwner: destination.owner | "Unknown"
  destinationWorkloadName: destination.workload.name | "Unknown"
  destinationWorkloadNamespace: destination.workload.namespace | "Unknown"
  contextProtocol: context.protocol | "Unknown"
  apiProtocol: api.protocol | "Unknown"
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: edgetosd
  namespace: istio-system
spec:
  match: (context.reporter.kind | "inbound" == "inbound") && (context.protocol | "unknown" != "unknown")
  actions:
   - handler: context-handler.stackdriver
     instances:
     - default.edge
---
# Rule to send edge instances to the stackdriver handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: edgetosd-stage
  namespace: istio-system
spec:
  match: (context.reporter.kind | "inbound" == "inbound") && (context.protocol | "unknown" != "unknown")
  actions:
   - handler: context-handler-stage.stackdriver
     instances:
     - default.edge
---
