apiVersion: "config.istio.io/v1alpha2"
kind: logentry
metadata:
  name: accesslog-stackdriver
  namespace: istio-system
spec:
  severity: '"Info"'
  timestamp: request.time
  variables:
    originIp: origin.ip | ip("0.0.0.0")
    sourceIp: source.ip | ip("0.0.0.0")
    sourceService: source.service | ""
    sourceUser: source.user | source.uid | ""
    sourceNamespace: source.namespace | ""
    destinationIp: destination.ip | ip("0.0.0.0")
    destinationService: destination.service | ""
    destinationNamespace: destination.namespace | ""
    apiName: api.service | ""
    apiVersion: api.version | ""
    apiClaims: request.headers["sec-istio-auth-userinfo"]| ""
    apiKey: request.api_key | request.headers["x-api-key"] | ""
    requestOperation: api.operation | ""
    protocol: request.scheme | "http"
    method: request.method | ""
    url: request.path | ""
    responseCode: response.code | 0
    responseSize: response.size | 0
    requestSize: request.size | 0
    latency: response.duration | "0ms"
    connectionMtls: connection.mtls | false
    useragent: request.useragent | ""
    responseTimestamp: response.time
    tcpBytesReceived: connection.received.bytes | 0
    tcpBytesSent: connection.sent.bytes | 0
  monitored_resource_type: '"global"'
  monitoredResourceDimensions:
  # When using the global MR, this must be filled in, preferably matching the
  # project_id given above in stackdriver config.
    project_id: '"csm-metrics-test"'
---
apiVersion: "config.istio.io/v1alpha2"
kind: stackdriver
metadata:
  name: log-handler
  namespace: istio-system
spec:
  # pushInterval: 1m
  project_id: "csm-metrics-test"

  # Describes how to map Istio logs into Stackdriver.
  logInfo:
    accesslog-stackdriver.logentry.istio-system:
      httpMapping:
        status: responseCode
        requestSize: requestSize
        responseSize: responseSize
        latency: latency
        localIp: sourceIp
        remoteIp: destinationIp
      labelNames:
      - originIp
      - sourceIp
      - sourceService
      - sourceUser
      - sourceNamespace
      - destinationIp
      - destinationService
      - destinationNamespace
      - apiName
      - apiVersion
      - apiClaims
      - apiKey
      - requestOperation
      - protocol
      - method
      - url
      - responseCode
      - responseSize
      - requestSize
      - latency
      - connectionMtls
      - useragent
      - responseTimestamp
      - tcpBytesReceived
      - tcpBytesSent
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: stackdriver-log
  namespace: istio-system
spec:
  actions:
  - handler: log-handler.stackdriver
    instances:
    - accesslog-stackdriver.logentry
---
