apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: pinger-istio-system
  namespace: istio-system
  labels:
    app: pinger
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinger-service-account
  namespace: istio-system
  labels:
    app: pinger
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pinger-istio-system
  labels:
    app: pinger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pinger-istio-system
subjects:
  - kind: ServiceAccount
    name: pinger-service-account
    namespace: istio-system
---
##################################################################################################
# Pinger
##################################################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pinger
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pinger
    spec:
      serviceAccountName: pinger-service-account
      containers:
      - name: pinger
        image: gcr.io/csm-metrics-test/pinger
        imagePullPolicy: IfNotPresent
---
