##################################################################################################
# Svc A
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: svc-a
  labels:
    app: svc-a
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: svc-a
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svc-a
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svc-a
    spec:
      containers:
      - name: svc-a
        image: gcr.io/istio-stackdriver/svc-a:head
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        args:
        - --port
        - "80"
---
##################################################################################################
# Svc B
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: svc-b
  labels:
    app: svc-b
spec:
  ports:
  - port: 50051
    name: grpc
  selector:
    app: svc-b
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svc-b
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svc-b
    spec:
      containers:
      - name: svc-b
        image: gcr.io/istio-stackdriver/svc-b:head
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
---
##################################################################################################
# Svc C
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: svc-c
  labels:
    app: svc-c
spec:
  ports:
  - port: 23333
    name: tcp
  selector:
    app: svc-c
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svc-c
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svc-c
    spec:
      containers:
      - name: svc-c
        image: gcr.io/istio-stackdriver/svc-c:head
        imagePullPolicy: Always
        ports:
        - containerPort: 23333
---
###########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: svc-a
          servicePort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo
spec:
  hosts:
  - "*"
  gateways:
  - demo-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: svc-a
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-ext
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-ext
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
---