##################################################################################################
# Svc A
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: svc-a
  labels:
    app: svc-a
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: svc-a
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svc-a
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svc-a
    spec:
      containers:
      - name: svc-a
        image: gcr.io/istio-stackdriver/svc-a:head
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        args:
        - --port
        - "80"
---
##################################################################################################
# Svc B
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: svc-b
  labels:
    app: svc-b
spec:
  ports:
  - port: 50051
    name: grpc
  selector:
    app: svc-b
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svc-b
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svc-b
    spec:
      containers:
      - name: svc-b
        image: gcr.io/istio-stackdriver/svc-b:head
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
---
##################################################################################################
# Svc C
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: svc-c
  labels:
    app: svc-c
spec:
  ports:
  - port: 23333
    name: tcp
  selector:
    app: svc-c
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svc-c
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svc-c
    spec:
      containers:
      - name: svc-c
        image: gcr.io/istio-stackdriver/svc-c:head
        imagePullPolicy: Always
        ports:
        - containerPort: 23333
---
##################################################################################################
# Svc Ngnix
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
      containers:
      - name: nginxhttps
        image: ymqytw/nginxhttps:1.5
        command: ["/home/auto-reload-nginx.sh"]
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
---
###########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 23333
      name: http-dashboard
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 9090
      name: http-prom
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: tcp
      protocol: TCP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo
spec:
  hosts:
  - "*"
  gateways:
  - demo-gateway
  http:
  - match:
    - uri:
        prefix: "/"
      port: 23333
    route:
    - destination:
        host: grafana.istio-system.svc.cluster.local
        port:
          number: 3000
  - match:
    - uri:
        prefix: "/"
      port: 9090
    route:
    - destination:
        host: prometheus.istio-system.svc.cluster.local
        port:
          number: 9090
  - match:
    - uri:
        exact: "/"
      port: 80
    route:
    - destination:
        host: svc-a
        port:
          number: 80
  - match:
    - uri:
        exact: "/nginx"
      port: 80
    rewrite:
      uri: "/index.html"
    route:
    - destination:
        host: nginxsvc
        port:
          number: 80
  tcp:
  - match:
    - port: 443
    route:
    - destination:
        host: nginxsvc
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-ext
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
---